//
// Generated file, do not edit! Created by opp_msgc 3.4 from netpkt.msg.
//

#ifndef _NETPKT_M_H_
#define _NETPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0304
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif


/**
 * Class generated from <tt>netpkt.msg</tt> by opp_msgc.
 * <pre>
 * message NetPkt
 * {
 *     fields:
 *         int srcAddress;
 *         int destAddress;
 * };
 * </pre>
 */
class NetPkt : public cMessage
{
  protected:
    int srcAddress_var;
    int destAddress_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NetPkt&);

  public:
    NetPkt(const char *name=NULL, int kind=0);
    NetPkt(const NetPkt& other);
    virtual ~NetPkt();
    NetPkt& operator=(const NetPkt& other);
    virtual cPolymorphic *dup() const {return new NetPkt(*this);}
    virtual void netPack(cCommBuffer *b);
    virtual void netUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcAddress() const;
    virtual void setSrcAddress(int srcAddress_var);
    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress_var);
};

inline void doPacking(cCommBuffer *b, NetPkt& obj) {obj.netPack(b);}
inline void doUnpacking(cCommBuffer *b, NetPkt& obj) {obj.netUnpack(b);}

#endif // _NETPKT_M_H_
