//
// Generated file, do not edit! Created by opp_msgc 3.4 from telnetpkt.msg.
//

#ifndef _TELNETPKT_M_H_
#define _TELNETPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0304
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{ ... }} section:

#include "netpkt_m.h"
// end cplusplus


/**
 * Class generated from <tt>telnetpkt.msg</tt> by opp_msgc.
 * <pre>
 * message TelnetPkt extends NetPkt
 * {
 *     fields:
 *         string payload;
 * };
 * </pre>
 */
class TelnetPkt : public NetPkt
{
  protected:
    opp_string payload_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TelnetPkt&);

  public:
    TelnetPkt(const char *name=NULL, int kind=0);
    TelnetPkt(const TelnetPkt& other);
    virtual ~TelnetPkt();
    TelnetPkt& operator=(const TelnetPkt& other);
    virtual cPolymorphic *dup() const {return new TelnetPkt(*this);}
    virtual void netPack(cCommBuffer *b);
    virtual void netUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload_var);
};

inline void doPacking(cCommBuffer *b, TelnetPkt& obj) {obj.netPack(b);}
inline void doUnpacking(cCommBuffer *b, TelnetPkt& obj) {obj.netUnpack(b);}

#endif // _TELNETPKT_M_H_
