//
// Generated file, do not edit! Created by opp_msgc 3.4 from hcpacket.msg.
//

#ifndef _HCPACKET_M_H_
#define _HCPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0304
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif


/**
 * Class generated from <tt>hcpacket.msg</tt> by opp_msgc.
 * <pre>
 * message HCPacket
 * {
 *     fields:
 *        int srcAddress;
 *        int destAddress;
 *        int hops = 0;
 * };
 * </pre>
 */
class HCPacket : public cMessage
{
  protected:
    int srcAddress_var;
    int destAddress_var;
    int hops_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HCPacket&);

  public:
    HCPacket(const char *name=NULL, int kind=0);
    HCPacket(const HCPacket& other);
    virtual ~HCPacket();
    HCPacket& operator=(const HCPacket& other);
    virtual cPolymorphic *dup() const {return new HCPacket(*this);}
    virtual void netPack(cCommBuffer *b);
    virtual void netUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcAddress() const;
    virtual void setSrcAddress(int srcAddress_var);
    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress_var);
    virtual int getHops() const;
    virtual void setHops(int hops_var);
};

inline void doPacking(cCommBuffer *b, HCPacket& obj) {obj.netPack(b);}
inline void doUnpacking(cCommBuffer *b, HCPacket& obj) {obj.netUnpack(b);}

#endif // _HCPACKET_M_H_
